server:
  port: 8082

spring:
  application:
    name: trip-service

  datasource:
    url: jdbc:postgresql://postgres:5432/taxi_db
    username: postgres
    password: postgres

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true